name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Development Image
        run: |
          docker build -t rrdentin/task5-productzilla:dev --target development .

      - name: Build Production Image
        run: |
          docker build -t rrdentin/task5-productzilla:prod --target production .

      - name: Push Development Image
        run: |
          docker push rrdentin/task5-productzilla:dev

      - name: Push Production Image
        run: |
          docker push rrdentin/task5-productzilla:prod
